version: "3.9"

services:
  backend:
    container_name: mypdfhero-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      FRONTEND_ORIGIN: "https://mypdfhero.com"
    # Only needed inside Docker (Caddy will reach this via the network)
    expose:
      - "4000"
    networks:
      - web

  frontend:
    container_name: mypdfhero-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "https://mypdfhero.com"
    depends_on:
      - backend
    expose:
      - "3000"
    networks:
      - web

networks:
  web:
    external: true
    # This is the network created by the corn infra compose:
    # "corn-ecommerce_web"
    name: corn-ecommerce_web
